### ISSUE TITLE
Using tags conversion feature breaks text styling

### ISSUE THREAD

**Issue by Branskugel** [ndy2/mkdocs-obsidian-support-plugin#47]
Tags conversion feature replaces hash symbol at the beginning of any color hex code making it impossible to use colors for e.g. highlighting text. Using escape symbol does not help, because the hex code stops working

**Comment by ndy2** [comment]
Hi. @Branskugel.

Thank you for open the issue.
Can you tell me what do you mean by `highlighting text with hex code` in mkdocs-material?

**Comment by Branskugel** [comment]
Hi!
Sure, I mean doing stuff like this

`example <span style="background:#ff4d4f">highlighted</span> text`

**Comment by Branskugel** [comment]
Had to resort to manually convert hex colors to hsl() or rgb(), but it's a bit tedious, obviously. Plus they seem to not work in conjunction with <font> tag for coloring text itself

**Comment by ndy2** [comment]
That is a good request!
I will fix it within this weekend.

**Comment by ndy2** [comment]
v1.4.1 released with an improvement - #48/ Exclude HTML from being converted in Markdown

Above example is tested in my local environment.
![image](https://github.com/user-attachments/assets/3022852e-8340-4a53-9088-284b6f477147)


Instead of targeting `tag conversion` with `span` tag, I think plugin needs to `Exclude all HTML from being converted`.
But the implementation has a little limitation. see [#49 ](https://github.com/ndy2/mkdocs-obsidian-support-plugin/pull/49#discussion_r1768641134)
